### ISSUE TITLE
在这个主题下引用此库，崩溃

### ISSUE THREAD

**Issue by Jacky-Xu** [getActivity/TitleBar#41]
Theme.MaterialComponents.DayNight.NoActionBar

报错信息如下：
android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.hjq.bar.TitleBar

.technology.cheliang.storage.ui.activity.login.RegisterActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.hjq.bar.TitleBar
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.hjq.bar.TitleBar

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
